
export class Ascii{
    public asciiConverter(convert){
        convert = convert.toString()
        switch(convert){
            case "0":
                return "NUL"
            case "1":
                return "SOH"
            case "2":
                return "STX"
            case "3":
                return "ETX"
            case "4":
                return "EOT"
            case "5":
                return "ENQ"
            case "6":
                return "ACK"
            case "7":
                return "BEL"
            case "8":
                return "BS"
            case "9":
                return "HT"
            case "A":
                return "LF"
            case "B":
                return "VT"
            case "C":
                return "FF"
            case "D":
                return "CR"
            case "E":
                return "SO"
            case "F":
                return "SI"
            case "10":
                return "DLE"
            case "11":
                return "DC1"
            case "12":
                return "DC2"
            case "13":
                return "DC3"
            case "14":
                return "DC4"
            case "15":
                return "NAK"
            case "16":
                return "SYN"
            case "17":
                return "ETB"
            case "18":  
                return "CAN"
            case "19":
                return "EM"
            case "1A":
                return "SUB"
            case "1B":
                return "ESC"
            case "1C":
                return "FS"
            case "1D":
                return "GS"
            case "1E":
                return "RS"
            case "1F":
                return "US"
            case "20":
                return " "
            case "21":
                return "!"
            case "22":
                return '"'
            case "23":
                return "#"
            case "24":
                return "$"
            case "25":
                return "%"
            case "26":
                return "&"
            case "27":
                return "'"
            case "28":
                return "("
            case "29":
                return ")"
            case "2A":
                return "*"
            case "2B":
                return "+"
            case "2C":
                return ","
            case "2D":
                return "-"
            case "2E":
                return "."
            case "2F":
                return "/"
            case "30":
                return "0"
            case "31":
                return "1"
            case "32":
                return "2"
            case "33":
                return "3"
            case "34":
                return "4"
            case "35":
                return "5"
            case "36":
                return "6"
            case "37":
                return "7"
            case "38":
                return "8"
            case "39":
                return "9"
            case "3A":
                return ":"
            case "3B":
                return ";"
            case "3C":
                return "<"
            case "3D":
                return "="
            case "3E":
                return ">"
            case "3F":
                return "?"
            case "40":
                return "@"
            case "41":
                return "A"
            case "42":
                return "B"
            case "43":
                return "C"
            case "44":
                return "D"
            case "45":
                return "E"
            case "46":
                return "F"
            case "47":
                return "G"
            case "48":
                return "H"
            case "49":
                return "I"
            case "4A":
                return "J"
            case "4B": 
                return "K"
            case "4C":
                return "L"
            case "4D":
                return "M"
            case "4E":
                return "N"
            case "4F":
                return "O"
            case "50":
                return "P"
            case "51":
                return "Q"
            case "52":  
                return "R"
            case "53":
                return "S"
            case "54":
                return "T"
            case "55":
                return "U"
            case "56":
                return "V"
            case "57":
                return "W"
            case "58":
                return "X"
            case "59":
                return "Y"
            case "5A":
                return "Z"
            case "5B":
                return "["
            case "5C":
                return "\\"
            case "5D":
                return "]"
            case "5E":
                return "^"
            case "5F":
                return "_"
            case "60":
                return "`"
            case "61":
                return "a"
            case "62":
                return "b"
            case "63":
                return "c"
            case "64":
                return "d"
            case "65":
                return "e"
            case "66":
                return "f"
            case "67":
                return "g"
            case "68":
                return "h"
            case "69":
                return "i"
            case "6A":
                return "j"
            case "6B":
                return "k"
            case "6C":
                return "l"
            case "6D":
                return "m"
            case "6E":
                return "n"
            case "6F":
                return "o"
            case "70":
                return "p"
            case "71":
                return "q"
            case "72":
                return "r"
            case "73":
                return "s"
            case "74":
                return "t"
            case "75":
                return "u"
            case "76":
                return "v"
            case "77":
                return "w"
            case "78":
                return "x"
            case "79":
                return "y"
            case "7A":
                return "z"
            case "7B":
                return "{"
            case "7C":
                return "|"
            case "7D":
                return "}"
            case "7E":
                return "~"
            case "7F":
                return "DEL"
        }
    }
    constructor(){
    }
}